### ISSUE TITLE
Add pension contribution splits

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk-data#30]
We should be taking:

* Employee pension contributions from `JOB.DEDUC1 * 52` (`UDEDUC1` is mostly null)
* Personal pension contributions from `PENPROV.PENAMT` where `STEMPPEN == 5` (this is pretty much all records with values)

Just confirmed that the latest FRS seems in line with both [personal](https://www.gov.uk/government/statistics/personal-and-stakeholder-pensions-statistics/private-pension-statistics-commentary) and [employee](https://www.gov.uk/government/statistics/workplace-pension-participation-and-savings-trends-2009-to-2022/workplace-pension-participation-and-savings-trends-of-eligible-employees-2009-to-2022) totals below:

<img width="805" alt="image" src="https://github.com/user-attachments/assets/7511cb82-0bb2-4769-ac48-613fd4a7ba80">

<img width="793" alt="image" src="https://github.com/user-attachments/assets/13ef14d0-fd7a-4469-9927-cc3cd1c55095">

Employer pensions aren't in the FRS or the SPI, so we're going to have to impute them. I'd suggest that we follow, as a first approach for now, the percentage match from the data above: employer contributions are 160% of employee contributions.

**Comment by vahid-ahmadi** [comment]
"However, by law, you and your staff have to pay a minimum amount into your scheme. This is set at 8% of your member of staff's earnings. You, the employer, must pay at least 3% of this, but you can choose to pay more."

It says almost the same. For the estimation, 160% of employee contributions are ok.
